config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :leagues
  resources :players
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/league.rb
class League < ApplicationRecord
  # include PgSearch::Model
  # pg_search_scope :search_by_name_and_address,
  #   against: [ :name, :address ],
  #   using: {
  #     tsearch: { prefix: true }
  #   }
  # multisearchable against: [:name, :address]
  searchkick
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_many :players, dependent: :destroy
  validates :name, presence: true
  validates :stars, presence: true
  validates :address, presence: true
  has_one_attached :photo
  belongs_to :user
end

app/models/player.rb
class Player < ApplicationRecord
  validates :name, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :leagues, dependent: :destroy
  has_many :players, through: :leagues
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  include Pundit
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  def index
    #@leagues = League.all
    @leagues = League.geocoded
    @markers = @leagues.map do |league|
      {
        lat: league.latitude,
        lng: league.longitude
      }
    end
    @leagues = policy_scope(League)
  end

  def show
    @league = League.find(params[:id])
    authorize @league
  end

  def new
    @league = League.new
    authorize @league
  end

  def create
    #league = League.new(league_params)
    @league = current_user.leagues.build(league_params)
    authorize @league
    @league.save
    redirect_to leagues_path
  end

  def edit
    @league = League.find(params[:id])
    authorize @league
  end

  def update
    @league = League.find(params[:id])
    @league.update(league_params)
    authorize @league
    redirect_to leagues_path
  end

  def destroy
    @league = League.find(params[:id])
    @league.delete
    authorize @league
    redirect_to leagues_path
  end

private

def league_params
  params.require(:league).permit(:name, :stars, :photo, :address)
end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  skip_after_action :verify_authorized, only: :home

  def home
  end

  def contact
  end

  def about
  end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  def index
    #@players = Player.all
    @players = policy_scope(Player)
  end

  def show
    @player = Player.find(params[:id])
    authorize @player
  end

  def new
    @player = Player.new
    authorize @player
  end

  def create
    #player = Player.create(player_params)
    @player = current_user.players.build(player_params)
    authorize @player
    @player.save
    redirect_to players_path
  end

  def edit
    @player = Player.find(params[:id])
    authorize @player
  end

  def update
    @player = Player.find(params[:id])
    @player.update(player_params)
    authorize @player
    redirect_to players_path
  end

  def destroy
    @player = Player.find(params[:id])
    @player.destroy
    authorize @player
    redirect_to players_path
  end

private

def player_params
  params.require(:player).permit(:name)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
     <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-162867946-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'UA-162867946-1');
    </script>
    <title>GeoTchoob : L'application pour vous retrouver entre amis, et faire des paris e-sport !</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="venez parier avec vos amis sur vos jeux-vidéos favoris!">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="google-site-verification" content="q9jK40lQLzX1azyGYm6D_OMw3aFx-bXDZcL0KA3xK7U" />
    <!-- <link href='https://api.mapbox.com/mapbox-gl-js/v1.8.1/mapbox-gl.css' rel='stylesheet' /> -->
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <!--p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>-->
    <%= yield %>
  </body>
</html>

app/views/leagues/edit.html.erb
<hr>

<hr>

<%= form_for @league do |f| %>
  <%= f.label :stars, "How many stars?" %>
  <%= f.number_field :stars%>
  <%= f.label :address, "Ou votre ligue se situe?" %>
  <%= f.text_field :address %>
  <%= f.submit %>
<% end %>

app/views/leagues/index.html.erb
<h1>Mes leagues</h1>

<hr>

<% @leagues.each do |league| %>
<h1><%= league.name %></h1>
<h3>nombre étoiles : <%= "*" * league.stars %> </h3>
<h3>addresse de la ligue : <%= league.address %> </h3>
<%= link_to "Aller voir", league_path(league) %>
<%= link_to "Supprimer", league_path(league), method: :delete, data: {confirm: "Êtes-vous sur?"} %>
<%= link_to "Editer", edit_league_path(league) %>


<hr>
<% end %>

<hr>


<%= link_to "Ajouter une nouvelle league", new_league_path  %>


<hr>

<div id="map"
data-markers="<%= @markers.to_json %>"
data-mapbox-api-key="<%= ENV["MAPBOX_API_KEY"] %>">
</div>

app/views/leagues/new.html.erb
<hr>
<hr>
<hr>

<div class="form">
  <%= simple_form_for @league, remote: true do |f| %>

  <%= f.label :name, "Your league name" %>
  <%= f.text_field :name %>

  <%= f.label :stars, "How many stars?" %>
  <%= f.number_field :stars%>
  <hr>
  <%= f.label :address, "Ou votre ligue se situe?" %>
  <%= f.text_field :address %>
  <hr>
  <%= f.input :photo, as: :file %>

  <%= f.submit %>

  <% end %>

app/views/leagues/show.html.erb
<h1><%= @league.name %></h1>
<h1><%= "*" * @league.stars %></h1>
<h1>adresse de la ligue : <%= @league.address %></h1>

<!--Cloudinary-->

<%= cl_image_tag @league.photo.key,
      width: 400, height: 300, crop: :fill %>

<hr>

<%= link_to "retour sur la liste", leagues_path %>

app/views/pages/home.html.erb
    <div class="home-banner">
      <h1>Bet & <p><span id="banner-typed-text"></span></p> </h1>
      <h2>Bienvenue sur la première application pour parier sur les matchs en e-sport </h2>
        <div class="formgroup">
          <%= form_tag leagues_path, method: :get do %>
          <%= text_field_tag :query,
          params[:query],
          id: "league_address", class: "form-control input",
          placeholder: "Choisis ta ville de rencontre et défis tes adversaires.."
          %>
          <% end %>
        </div>
    </div>



<div class="container">
<div class="cards">
    <div class="card" style="width: 18rem;">
      <img class="card-img-top" src="https://fr.web.img6.acsta.net/r_640_360/newsv7/19/10/17/09/38/4404050.jpg" alt="Card image cap">
      <div class="card-body">
        <h5 class="card-title">League Of Legend</h5>
        <p class="card-text">Rejoignez cette ligue, et pariez sur les matchs de League of legend e-sport!</p>
        <a href="#" class="btn btn-primary">Rejoindre</a>
      </div>
    </div>

    <div class="card" style="width: 18rem;">
      <img class="card-img-top" src="https://images.dexerto.fr/uploads/thumbnails/_thumbnailLarge/WoW-Classic-Ad-ons-mods.jpg" alt="Card image cap">
      <div class="card-body">
        <h5 class="card-title">World Of Warcraft</h5>
        <p class="card-text">Rejoignez cette ligue, et pariez sur les matchs de Worl of Warcraft e-sport!</p>
        <a href="#" class="btn btn-primary">Rejoindre</a>
      </div>
    </div>

    <div class="card" style="width: 18rem;">
      <img class="card-img-top" src="https://geeko.lesoir.be/wp-content/uploads/sites/58/2020/03/960x0.png" alt="Card image cap">
      <div class="card-body">
        <h5 class="card-title">Call of Duty</h5>
        <p class="card-text">Rejoignez cette ligue, et pariez sur les matchs de Call of Duty e-sport!</p>
        <a href="#" class="btn btn-primary">Rejoindre</a>
      </div>
    </div>
</div>

  <div class="exemple">
    <hr>
    <% if user_signed_in? %>
    <h1> Bienvenu <%= current_user.email %>
      <% end %>
    </h1>
    <hr>
    <h2> Rejoignez plus de 100 000 joueurs !</h2>
    <hr>
    <h3> Retrouvez vos jeux vidéos préférés !</h3>
    <hr>
    <h4> Faites dès maintenant partie de l'aventure !</h4>
    <hr>
    <h2> La seule application avec Paypal en paiement</h1>
    <hr>

  </div>

</div>

app/views/players/edit.html.erb
<%= form_for @player do |f| %>
  <%= f.label :name, "Your bet name?" %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/players/index.html.erb
<h1>Tes paris</h1>

<hr>

<% @players.each do |player| %>
<h2><%= player.name %></h2>
<%= link_to "Aller voir", player_path(player) %>
<%= link_to "Supprimer", player_path(player), method: :delete, data: {confirm: "Êtes-vous sur?"} %>
<%= link_to "Editer", edit_player_path(player) %>
<% end %>
<hr>

<%= link_to "Ajouter un nouveau pari", new_player_path  %>

app/views/players/new.html.erb
<hr>

<hr>

<%= simple_form_for @player do |f| %>
  <%= f.label :name, "Your bet name?" %>
  <%= f.text_field :name %>
  <%= f.submit "let's go" %>
<% end %>

app/views/players/show.html.erb
<h1><%= @player.name %></h1>

<hr>

<%= link_to "retour sur la liste", players_path %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <%= link_to "root_path", class: "navbar-brand" do %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>



      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <% if user_signed_in? %>
          <div class="home">
            <li class="nav-item active">
              <%= link_to "Home", "/", class: "nav-link" %>
            </li>
          </div>
            <li class="nav-item">
              <%= link_to "Mes Leagues", leagues_path, class: "nav-link" %>
            </li>

            <li class="nav-item">
              <%= link_to "Mes Paris", players_path, class: "nav-link" %>
            </li>


            <li class="nav-item dropdown">
              <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </div>
            </li>
    <% else %>
            <li class="nav-item-login">
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            </li>
            <% end %>
        </ul>
      </div>
</div>